### ISSUE TITLE
Add repositories not hosted in MaastrichtU-IDS GitHub organization

### ISSUE THREAD

**Issue by vemonet** [MaastrichtU-IDS/projects#2]
Add possibility to add repositories that are not from MaastrichtU-IDS on GitHub. They will be considered as a project repository, the DOAP file will be integrated, and the releases monitored

**Comment by carlosug** [comment]
@demo for DOAP workshop. External repository:
Link: [https://github.com/carlosug/IDS-RDM-202019-FSFDAWR](https://github.com/carlosug/IDS-RDM-202019-FSFDAWR)

carlosug/IDS-RDM-202019-FSFDAWR

**Comment by vemonet** [comment]
Repositories external to MaastrichtU-IDS GitHub organization can be added in this file: https://github.com/MaastrichtU-IDS/projects/blob/main/EXTERNAL_REPOSITORIES.txt
